apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: filtron
    name: filtron
    namespace: searx
  spec:
    clusterIP: None
    ports:
    - port: 4040
      protocol: TCP
      targetPort: 4040
    selector:
      app: filtron
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: morty
    name: morty
    namespace: searx
  spec:
    clusterIP: None
    ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: morty
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: searx
    name: searx
    namespace: searx
  spec:
    clusterIP: None
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: searx
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: filtron
    name: filtron
    namespace: searx
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: filtron
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: filtron
      spec:
        containers:
        - args:
          - -listen
          - 0.0.0.0:4040
          - -api
          - 0.0.0.0:4041
          - -target
          - searx.searx.svc.cluster.local:8080
          image: dalf/filtron
          imagePullPolicy: IfNotPresent
          name: filtron
          ports:
          - containerPort: 4040
            name: filtron
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
    labels:
      app: morty
    name: morty
    namespace: searx
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: morty
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: morty
      spec:
        containers:
        - args:
          - -listen
          - 0.0.0.0:3000
          - -timeout
          - "6"
          - -ipv6
          env:
          - name: MORTY_KEY
            value: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
          image: dalf/morty
          imagePullPolicy: IfNotPresent
          name: morty
          ports:
          - containerPort: 3000
            name: morty
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
    labels:
      app: searx
    name: searx
    namespace: searx
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: searx
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: searx
      spec:
        containers:
        - image: searx/searx
          imagePullPolicy: IfNotPresent
          name: searx
          ports:
          - containerPort: 8080
            name: searx
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/searx
            name: searx
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: uwsgi.ini
              path: uwsgi.ini
            - key: settings.yml
              path: settings.yml
            name: searx
          name: searx
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
---
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: nginx
    labels:
      app: searx
    name: searx
    namespace: searx
  spec:
    rules:
    - host: searx.travnewmatic.com
      http:
        paths:
        - backend:
            serviceName: filtron
            servicePort: 4040
          path: /
        - backend:
            serviceName: morty
            servicePort: 3000
          path: /morty
    tls:
    - hosts:
      - searx.travnewmatic.com
      secretName: searx.travnewmatic.com
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
